FROM golang:1.17-alpine AS buildenv

RUN apk add --no-cache git make build-base

WORKDIR /app/koal

COPY server/go.mod .
COPY server/go.sum .
RUN go mod download

COPY server/. .
RUN GOOS=linux GOARCH=amd64 go build -o ./bin ./cmd/main.go

FROM alpine

WORKDIR /app/koal

COPY server/config.env ./
COPY ./api-docs ../api-docs
COPY --from=buildenv  /app/koal/bin ./bin
EXPOSE 8090
CMD ["./bin"]
