on:
  push:
    branches:
      - master
name: Deploy Production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "koal-todo"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
