name: Deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy action step
        uses: Glyphack/doprax-deploy-action@v0.1.0-alpha.0
        with:
          email: ${{ secrets.DOPRAX_EMAIL }}
          password: ${{ secrets.DOPRAX_PASSWORD }}
          api_key: ${{ secrets.DOPRAX_API_KEY}}
          project_name: "koal-final"
